// const mongoose = require("mongoose");

// const CommentSchema = new mongoose.Schema({
//   authorId: { type: String, required: true },      // employeeId or user id
//   authorName: { type: String, required: true },
//   role: { type: String, enum: ["Employee", "Manager", "HR"], default: "Employee" },
//   message: { type: String, required: true },
//   createdAt: { type: Date, default: Date.now },
// });

// const TaskSchema = new mongoose.Schema({
//   id: { type: String, required: true, unique: true }, // client-side id or uuid
//   employeeId: { type: String, required: true },       // which employee this task belongs to
//   fy: { type: String, required: true },               // FY-25 etc
//   text: { type: String, required: true },             // task text/summary
//   assigned: { type: String },                         // assigned by whom
//   assignedDate: { type: Date, default: Date.now },
//   dueDate: { type: Date },
//   rating: { type: Number, min: 0, max: 5, default: 0 },
//   score: { type: Number, min: 0, max: 5, default: 0 },
//   status: { type: String, enum: ["Open", "In Progress", "Completed"], default: "Open" },
//   comments: [CommentSchema],
//   createdAt: { type: Date, default: Date.now },
//   updatedAt: { type: Date, default: Date.now },
// });

// TaskSchema.pre("save", function (next) {
//   this.updatedAt = Date.now();
//   next();
// });

// module.exports = mongoose.model("Task", TaskSchema);
const mongoose = require("mongoose");

const CommentSchema = new mongoose.Schema({
  text: { type: String, required: true },
  author: { type: String, enum: ["Manager", "Employee"], required: true },
  timestamp: { type: Date, default: Date.now },
  edited: { type: Boolean, default: false },
  // id is generated by mongoose _id for each subdoc; but keep a string id if you prefer:
  cid: { type: String, default: () => Date.now().toString(36) + Math.random().toString(36).slice(2,7) }
});

const TaskSchema = new mongoose.Schema(
  {
    text: { type: String, required: true },
    assignedBy: { type: String, required: true }, // manager or TL name/id string
    assignedById: { type: String }, // optional id
    assignedTo: { type: String, required: true }, // employee id
    assignedDate: { type: Date, default: Date.now },
    assignedDateTime: { type: Number, default: () => Date.now() }, // ms used for 24-hour checks
    dueDate: { type: Date },
    fy: { type: String, required: true }, // e.g. "FY (25 - 26)"
    rating: { type: Number, min: 0, max: 5, default: 0 },
    managerEdited: { type: Boolean, default: false }, // true if manager set rating
    comments: { type: [CommentSchema], default: [] },
    // soft-delete flag if needed
    archived: { type: Boolean, default: false }
  },
  { timestamps: true }
);

module.exports = mongoose.model("Task", TaskSchema);
